
language: bash
sudo: false
notifications:
  
install:
  - git clone -b master https://github.com/Freifunk-gluon/gluon /home/travis/build/freifunk-troisdorf/gluon 
  - git clone -b master  https://github.com/Delta1977/Gluon-Site-Tdf /home/travis/build/freifunk-troisdorf/gluon/site
script: 
 - wget https://raw.githubusercontent.com/Freifunk-Troisdorf/build-fw/master/site_check.sh && chmod +x site_check.sh
 - ./site_check.sh
